### ISSUE TITLE
Unable to generate the JSON file from the excel file

### ISSUE THREAD

**Issue by vijaygopal** [stevetarver/excel-as-json#44]
Hi,

Given below is the code snippet that I am using to generate the json file from the attached excel file. 
NodeJS Version - v10.15.0

const convertexcel = require('excel-as-json').processFile
convertexcel('C:/RTC/METS_DEV_FUTURE/Get_Insured_Test_Data_Creator/Test_Data.xlsx','C:/RTC/METS_DEV_FUTURE/Get_Insured_Test_Data_Creator/Test_Data_New.json',{'isColOriented':true},()=>{
    console.log('Completed')
})

When I execute the above code I keep getting the  below error - 

C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator>node temp.js
C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\node-promise\promise.js:204
          throw error;
          ^

TypeError: Cannot read property 'length' of undefined
    at transpose (C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\excel-as-json\lib\excel-as-json.js:153:37)
    at convert (C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\excel-as-json\lib\excel-as-json.js:172:14)
    at C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\excel-as-json\lib\excel-as-json.js:283:20
    at C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\excel-as-json\node_modules\excel\excelParser.js:163:3
    at Immediate.<anonymous> (C:\RTC\METS_DEV_FUTURE\Get_Insured_Test_Data_Creator\node_modules\node-promise\promise.js:164:27)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

Could you please let me know what I am doing incorrectly?

[Test_Data.xlsx](https://github.com/stevetarver/excel-as-json/files/2748067/Test_Data.xlsx)

**Comment by vinayuig** [comment]
Hi Vijay ,Even i am going through same issue .Any solution found for this? Please let me know

**Comment by eightbit** [comment]
This package has stopped working for me. I get an empty array as the result: [].
reinstall with npm fails. reinstall with yarn throws errors but excel-as-json does run and produce an empty array []

**Comment by SophiaHan6** [comment]
try this [https://github.com/stevetarver/excel-as-json/issues/46](url)

**Comment by stevetarver** [comment]
@vijaygopal I have not tested in node v10.15.0. Historically, deleting your npm packages and reinstalling has fixed these problems.

I will not have time to look into this error in the near future but will leave this issue open for when I get time.
