### ISSUE TITLE
Doesn't work on Latest NodeJS

### ISSUE THREAD

**Issue by ghost** [stevetarver/excel-as-json#47]
Besides nodejs, do you have any prerequisite for installing this software?

**Comment by leduclinh7141** [comment]
I have same problem. Do you have any solution? I worked fine on node 8.

**Comment by ghost** [comment]
The main reason is here, also happened on CentOS:
Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v67-linux-x64.tar.gz 

Check from here: https://github.com/libxmljs/libxmljs/releases/ , I didn't see the required gz file. Either we are able to modify the npm install command for this package or we redirect the libxmljs to the version of our choice. Will try again tomorrow.

**Comment by leduclinh7141** [comment]
Can you give me how to modify the npm install command for this package? What version of Node you are using? I am trying with version 10 lts. Thank for you help.

**Comment by stevetarver** [comment]
There are no additional prereqs for this package. It has always worked with a simple npm install, although I have not actually installed with v10 yet. Note: I will likely not get to testing this in the foreseeable future, but will leave this issue open for when I have time.

**Comment by timbergus** [comment]
Hi. I'm trying with __node@12.3.1__ and __npm@6.9.0__ in a Mac with __macOS@10.14.5__. The message I have is:

```bash
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.8 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v72-darwin-x64.tar.gz
```

And then, when trying to build it, everything goes to hell.

```bash
[...]
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
[...]
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
[...]
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
[...]
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
[etc]
```

With this final message:

```bash
10 warnings and 12 errors generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs
node-pre-gyp ERR! node -v v12.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/Gustavo/Documents/xxxxxxxxxx/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Gustavo/.npm/_logs/2019-05-28T12_33_23_310Z-debug.log
```

**Comment by herroldreal** [comment]
I have same problem. Do you have any solution?

**Comment by adil-ahorger** [comment]
There is now a new version of the [excel](https://www.npmjs.com/package/excel) package, which uses the newest version of libxmljs, and this error doesn't occur on that version. 

I have a fork of this repo [here](https://github.com/adil-ahorger/excel-as-json) that uses a copy of the old "excel" version and the newest libxmljs version, and it installs with no issues. I haven't done extensive testing, so I'm not sure if it works 100% of the time, but it works for my use case.

Can someone update this package to use `excel v1.0.1`?
