### ISSUE TITLE
can you please provide the details to setup this project?

### ISSUE THREAD

**Issue by baggiaraj** [stevetarver/excel-as-json#51]
I have tried to install and execute. it's showing some issues. can i get the detailed instruction to configure this API.

issue:

d:\ExcelProject\exceljson>node excel-as-json.js (not finding this module file)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'd:\ExcelProject\exceljson\lib\excel-as-json.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by stevetarver** [comment]
Standard instructions for use are on the GH main page: https://github.com/stevetarver/excel-as-json.

Debugging is as with any node module or project.
